---
# tasks file for nginx
- name: install the nginx rpm from a remote repo
  yum:
    name: "{{ item }}"
    disable_gpg_check: yes
  with_items:
    - "http://nginx.org/packages/centos/7/x86_64/RPMS/nginx-1.14.0-1.el7_4.ngx.x86_64.rpm"
  tags:
    - nginx

- yum:
    name: nginx
    state: present
  notify: nginxStart
  tags:
    - nginx

- name: nginx config
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - nginx

- name: make directory
  file:
    path: "/var/log/nginx/{{ HOST_ID }}"
    mode: 0755
    state: directory

