version: "3.7"
services:
  chatapi: &app_base
    build:
      context: ../omotenashi-pf-chatapi
      dockerfile: ./Dockerfile
    depends_on:
      - mssql
    tty: true
    stdin_open: true
    env_file:
      - ./env/development.env
    container_name: chatapi
    environment:
      API_TYPE: chatapi
      RAILS_ENV: development
      RACK_ENV: development
      BUNDLE_PATH: /usr/local/bundle
      RAILS_MASTER_KEY: 1796d54f53be1a4638fe22a7685cc2b8
      DB_USER: omouser
      DB_NAME: chat
      DB_HOST: mssql
      DB_PORT: 1433
      BLOB_ACC_NAME: acjpenpomosta02
      BLOB_ACCESS_KEY: OiVXg1KFKDCnjsB4zax7/NLlt94RJ25H+XcKN0g4XQ0AFiwBZQN/siO0buuJQlgSQjI+iGZpnNTDReOAN/++bw==
      BLOB_CONTAINER_NAME: conversation-histories
    ports:
      - "3000:3000"
    command: bash -c "bundle install && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ../omotenashi-pf-chatapi:/app
      - bundle:/usr/local/bundle
      - chatapi-tmp:/app/tmp
  # chatapi-cronjob:
  #   <<: *app_base
  #   container_name: chatapi-cronjob
  #   ports:
  #     - 3100:3100
  #   command: bash -c "bundle exec whenever --update-crontab && cron -f"
  #   volumes:
  #     - ../omotenashi-pf-chatapi:/app
  #     - bundle:/usr/local/bundle
  #     - chatapi-cronjob-tmp:/app/tmp
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: P@ssw0rd2017
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/opt/mssql
      - ./sqls:/sqls
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.chatapi-nginx
      args:
        APP_ENV: development
        TYPE: chatapi
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - chatapi
volumes:
  bundle:
    driver: local
  chatapi-tmp:
    driver: local
  mssql-data:
    driver: local
  # chatapi-cronjob-tmp:
