FROM nginx:latest

ARG TYPE
ARG APP_ENV
COPY "files/crt/${TYPE}-${APP_ENV}.crt" /etc/nginx/ssl/web.crt
COPY "files/crt/${TYPE}-${APP_ENV}.key" /etc/nginx/ssl/web.key

RUN chmod 755 /etc/nginx/ssl/web.crt
RUN chmod 700 /etc/nginx/ssl/web.key

COPY files/chatapi-nginx.${APP_ENV} /etc/nginx/conf.d/default.conf
