---
# tasks file for nginx
- name: install the nginx rpm from a remote repo
  yum: name={{item}}
  with_items:
    - http://nginx.org/packages/centos/7/x86_64/RPMS/nginx-1.14.0-1.el7_4.ngx.x86_64.rpm
  tags:
    - nginx

- yum:
    name: nginx
    state: present
  notify: nginxStart
  tags:
    - nginx

- name: make certs directory
  file:
    path: /etc/pki/tls/certs
    mode: 0700
    owner: root
    group: root
    state: directory
  when: "'development' not in group_names"

- name: make private directory
  file:
    path: /etc/pki/tls/private
    mode: 0700
    owner: root
    group: root
    state: directory
  when: "'development' not in group_names"

- name: copy withjorge.crt file
  copy:
    dest: /etc/pki/tls/certs/withjorge.crt
    src: withjorge.crt
    mode: 0400
    owner: root
    group: root
  when: "'development' not in group_names"

- name: copy withjorge.key file
  copy:
    dest: /etc/pki/tls/private/withjorge.key
    src: withjorge.key
    mode: 0400
    owner: root
    group: root
  when: "'development' not in group_names"

- name: nginx config
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - nginx

- name: nginx site config
  template:
    src: "{{ STAGE }}.conf"
    dest: "/etc/nginx/conf.d/{{ HOST_ID }}.conf"
    owner: root
    group: root
    mode: 0644
  notify: nginxReload
  tags:
    - nginx

- name: make directory
  file:
    path: "/var/log/nginx/{{ HOST_ID }}"
    mode: 0755
    state: directory

- name: php fpm start
  service:
    name: php-fpm
    state: started
    enabled: yes
